# Generated by Django 4.2 on 2023-05-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='any',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='uid',
            new_name='user',
        ),
    ]
