# Generated by Django 4.2 on 2023-05-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_rename_any_wish_product_rename_uid_wish_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
