# Generated by Django 4.2 on 2023-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
