# Generated by Django 4.2 on 2023-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
