# Generated by Django 4.2 on 2023-05-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_register_table_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalQuantity', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('RemainingQuantity', models.IntegerField(default=1)),
            ],
        ),
    ]
