# Generated by Django 4.2 on 2023-05-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
