# Generated by Django 4.2 on 2023-05-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_rename_quantity_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product'),
        ),
    ]
