# Generated by Django 4.2 on 2023-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0013_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='contact',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
