# Generated by Django 4.2 on 2023-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0014_review_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contact',
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
