# Generated by Django 4.2 on 2023-05-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0015_alter_review_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cust_name',
        ),
    ]
