# Generated by Django 4.2 on 2023-05-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0016_remove_review_cust_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
